---
title: "R Notebook"
output: html_notebook
---

Import measurement data from Fiji

Tidy, filter stage and stains, and generate ratio values

```{r}
library(dplyr)
library(tidyr)
library(purrr)  

# Set the input directory and filtering metadata
data_path <- "csvs/"                   # path to csvs
stages <-  c("7ss", "8ss", "9ss")      # stages to INCLUDE
stains  <-  "SOX10"                   # measurement channel to analyze
outputname <- "20251120_dnFGFR1;pCIAPOD_Epistasis"

# Function to read and process a single file
read_and_process_file <- function(file_path) {

  # Read CSV
  data <- read.csv(file_path)

  # Extract metadata from filename
  file_name <- basename(file_path)
  file_parts <- strsplit(file_name, "_")[[1]]

  # Basic metadata (assuming stable positions)
  data$Date <- file_parts[1]
  data$Treatment <- file_parts[2]
  data$Embryo <- file_parts[4]
  data$Stage <- file_parts[5]
  data <- data %>%
  tidyr::separate(Label, into = c("Measurement", "Side"), sep = ":")
  
  # Embryo ID = Date_Treatment_Emb
  emb_id <- paste(file_parts[c(1, 2, 4, 5)], collapse = "_")
  data <- data %>% mutate(Emb_ID = emb_id)

  # Drop unnecessary columns if they exist
  data <- data %>%
  dplyr::select(-dplyr::any_of(c("Label", "X", "Area", "IntDen",  "RawIntDen")))
}

# Read, process, and combine all files
combined_df <- list.files(path = data_path, 
                         
                          full.names = TRUE) %>%
  map_df(read_and_process_file)

# Pivot wider to expand the "Side" column and transpose the "Mean" column
pivot_df <- combined_df %>%
  pivot_wider(names_from = Side, values_from = Mean) %>%
  # Calculate the ratio of Expt to Cntl
  mutate(Ratio = Expt / Cntl)

# Filter on stage and measurement channel
filtered_df <- pivot_df %>%
  filter(Stage %in% stages) %>%
  filter(Measurement %in% stains)

write.csv(filtered_df, paste0(outputname, "_filtered.csv"), row.names = FALSE)
```

Plot the results

```{r BoxandWhiskers}
library(ggplot2)
library(GGally)
library(ggbeeswarm)

# Create box and whiskers plot
boxplot <- ggplot(filtered_df, aes(x = Treatment, y = Ratio, fill=Date)) +
  geom_hline(yintercept = 1, linetype = "solid", color = "white") +  # Add line at y=1
  geom_hline(yintercept = 1, linetype = "dashed", color = "firebrick4") +  # Add line at y=1
  geom_boxplot(color = "black", fill = "white", alpha = 1,
                lwd = 1, width = 0.7, outlier.shape=NA) +
  geom_beeswarm(color = "black", 
                #fill = "darkgray", 
                alpha = 1, shape = 21, size = 3, 
                cex=5     # adjust me to change spread of datapoints
                ) +
  ylim(0, 2) + # Define Y axis upper and lower limits
  labs(x = "", y = "SOX10 Expression in Otic Placode \n(Experimental/Control)") +  # Hard code axis labels
  #scale_x_discrete(labels = expression(italic("APOD") ~ " MO")) +  # Hard code x column name
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = 16, color = "black"),
    axis.text.y = element_text(size = 14, color = "black"),
    axis.title = element_text(size = 14, color = "black"),
    axis.line = element_line(size = 0.7, color = "black"),  # Add black axis lines
    panel.grid.major.x = element_blank(),  # Remove grid lines
  )

# Display the box and whiskers plot
print(boxplot)

# Perform two-tailed paired t-test, print results
t_test_result <- t.test(filtered_df$Cntl, filtered_df$Expt, paired = TRUE)

# Calculate the difference between Expt and Cntl, 
# print SEM of diff and sample size for power analysis
difference <- filtered_df$Expt - filtered_df$Cntl
sem_difference <- sd(difference, na.rm = TRUE) / sqrt(length(difference))
cat("SEM of Difference:", sem_difference, "\n")
cat("Sample size:", length(filtered_df$Cntl), "\n")
print(t_test_result)
```

```{r ParallelCoordinatePlot}
# Define column names for subsequent parallel coordinate and jitter plotting
column_names <- c("Cntl", "Expt")
# Find column numbers for the specified column names, then produce a ratio column of Expt/Cntl
column_numbers <- which(names(filtered_df) %in% column_names)

# Create parallel coordinate plot
parallel_plot <- ggparcoord(filtered_df,
                             columns = column_numbers, # Indicate column numbers to compare
                             groupColumn = "Treatment",
                             scale = "globalminmax",
                             showPoints = TRUE,
                             alphaLines = 0.5) #+
                        #ylim(0,2)

# Customize plot labels and appearance
parallel_plot <- parallel_plot +
  labs(x = "Embryo Side", y = "SOX10 Expression in Otic Placode \n Experiment/Control") + # Remove title
  theme_minimal() +
  theme(axis.text = element_text(color = "black"), # Set axis text color to black
        axis.line = element_line(color = "black"), # Set axis line color to black
        panel.grid.major = element_blank(), # Remove major gridlines
        panel.grid.minor = element_blank()) # Remove minor gridlines

# Set point and line color to black
parallel_plot <- parallel_plot +
  scale_color_manual(values = "black") + # Set point color to black
  scale_alpha_manual(values = c(0.5)) + # Set line alpha to 0.5
  theme(panel.grid.major = element_blank(), # Remove major gridlines
        panel.grid.minor = element_blank()) # Remove minor gridlines

# Display the plot
print(parallel_plot)
```
