---
title: "R Notebook"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

```{r}
library(dplyr)
library(tidyr)
library(purrr)  # Load the purrr package

# Set the directory containing the data files
data_path <- "csvs/"

# Function to read and process a single file
read_and_process_file <- function(file_path) {
  # Read the file
  data <- read.csv(file_path)
  # Extract metadata from file name
  file_name <- basename(file_path)
  file_parts <- strsplit(file_name, "_")[[1]]
  data$Date <- file_parts[[1]]
  data$Stage <- file_parts[[5]]
  emb_id <- paste(file_parts[c(1, 2, 3, 4)], collapse = "_")
  
  # Extract "Cntl" or "Expt" from the column "Label" and assign to "Side"
  #data$Side <- ifelse(grepl("Cntl", data$Label), "Cntl", "Expt")
  
  # Extract "Probe" and "Side" values from the column "Label"
  data$Probe <- sapply(strsplit(data$Label, ":"), `[`, 1)
  data$Side <- sapply(strsplit(data$Label, ":"), `[`, 2)
  
  # Remove ".csv" from the "Stage" column if present
  data$Stage <- sub("\\.csv$", "", data$Stage)
  
  # Extract Treatment from file_parts
  condition <- file_parts[2]
  
  # Drop unnecessary columns
  data <- data %>%
    select(-Label, -X, -Area, -IntDen, -RawIntDen)
  
  # Return processed data
  return(data %>% mutate(Emb_ID = emb_id, Condition = condition))
}

# Read, process, and combine all files
combined_df <- list.files(path = data_path, full.names = TRUE) %>%
  map_df(read_and_process_file)

# Pivot wider to expand the "Side" column and transpose the "Mean" column
pivot_df <- combined_df %>%
  pivot_wider(names_from = Side, values_from = Mean) %>%
  # Calculate the ratio of Expt to Cntl
  mutate(Ratio = Expt / Cntl)

# Calculate normalization
normalized_df <- pivot_df %>%
  group_by(Date) %>%
  mutate(
    Norm_Cntl = Cntl / mean(Cntl),
    Norm_Expt = Expt / mean(Cntl)
  ) %>%
  ungroup()

# Split treatment condition and dose
normalized_df <- normalized_df %>% 
    # Splitting condition
    separate(Condition, into = c("Treatment", "Dose"), sep = ";")


# Print the pivoted dataframe
print(normalized_df)
date <- Sys.Date()
write.csv(normalized_df, paste0(date, " HCRFISH Results.csv"), row.names=FALSE)

``` 

```{r}
library(ggplot2)
library(GGally)
library(ggbeeswarm)

# Create box and whiskers plot
boxplot <- ggplot(normalized_df, aes(x = Probe, y = Ratio, fill=Date)) +
  geom_hline(yintercept = 1, linetype = "solid", color = "white") +  # Add line at y=1
  geom_hline(yintercept = 1, linetype = "dashed", color = "firebrick4") +  # Add line at y=1
  geom_boxplot(color = "black", fill = "white", alpha = 1,
                lwd = 1, width = 0.6, outlier.shape=NA) +
  geom_beeswarm(color = "black", 
                fill = "darkgray", 
                alpha = 1, shape = 21, size = 3, cex=3.5) +
  ylim(0, 1.7) + # Define Y axis upper and lower limits
  labs(x = "", y = "SOX10 Expression in Otic\nPlacode (Experimental/Control)") +  # Hard code axis labels
  # scale_x_discrete(labels = (expression(italic("APOD")~"MO", 
  #                                       "pCI"~italic("APOD")))) +  # Hard code x column name
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = 16, color = "black"),
    axis.text.y = element_text(size = 14, color = "black"),
    axis.title = element_text(size = 14, color = "black"),
    axis.line = element_line(size = 0.7, color = "black"),  # Add black axis lines
    panel.grid.major.x = element_blank(),  # Remove grid lines
  )

# Display the box and whiskers plot
print(boxplot)

# Perform two-tailed paired t-test, print results
t_test_result <- t.test(normalized_df$Cntl, normalized_df$Expt, paired = TRUE)
print(t_test_result)

# Calculate the difference between Expt and Cntl, 
# print SEM of diff and sample size for power analysis
difference <- normalized_df$Expt - normalized_df$Cntl
sem_difference <- sd(difference, na.rm = TRUE) / sqrt(length(difference))
cat("SEM of Difference:", sem_difference, "\n")
cat("Sample size:", length(normalized_df$Cntl), "\n")
```

